FROM php:7.4.3-fpm

ARG GID
ARG UID

WORKDIR /var/www

RUN apt-get update \
    && apt-get install -y \
        libfreetype6 \
        libjpeg62-turbo \
        libpng[0-9]+-[0-9]+$ \
        libxpm4 \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        libxpm-dev \
        libwebp[0-9]+$ \
        libwebp-dev \
        libzip[0-9]$ \
        cmake \
        gnutls-dev \
        libzip-dev \
        libbz2-dev \
        zlib1g-dev \
        libpq5 \
        libpq-dev \
    && docker-php-ext-install \
        gd \
        bcmath \
        mysqli \
        pdo_pgsql \
        pdo_mysql \
        pgsql \
        zip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -u $UID www-data \
    && groupmod -g $GID www-data

USER www-data
