version: "3.8"
services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile-${PHP_VERSION}
    volumes:
      - ${PROJECT_PATH}:/var/www
    expose:
      - "9000"

  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"

  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  nginx:
    image: nginx:${NGINX_VERSION}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ${PROJECT_PATH}:/var/www
    depends_on:
      - php-fpm
    ports:
      - "80:80"

volumes:
  mysql-data:
  postgres-data:
